FROM jenkins/jenkins:alpine

ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false

COPY --chown=jenkins:jenkins plugins.txt /usr/share/jenkins/ref/plugins.txt

COPY user.groovy /usr/share/jenkins/ref/init.groovy.d/user.groovy

RUN jenkins-plugin-cli -f /usr/share/jenkins/ref/plugins.txt






