# - name: Enabling NodeJS:18
#   ansible.builtin.shell: dnf module disable nodejs -y; dnf module enable nodejs:18 -y;

# - name: Installing NodeJS:18
#   ansible.builtin.package:
#     name: nodejs
#     state: present

# - name: Creating RoboShop User
#   ansible.builtin.user:
#     name: roboshop

# - name: Creating App Directory
#   ansible.builtin.file:
#     path: "/app/{{service}}"
#     state: directory

# - name: Downlaoding "{{service}}" service
#   ansible.builtin.unarchive:
#     src: "https://buildbucket5.s3.us-east-1.amazonaws.com/RoboShop/{{service}}.zip"
#     dest: "/app/{{ service }}"
#     remote_src: yes

# - name: Installing "{{service}}" service
#   ansible.builtin.shell: npm install
#   args:
#     chdir: "/app/{{service}}"

# - name: Configuring "{{service}}" service
#   ansible.builtin.template:
#     src: "{{service}}.service.j2"
#     dest: "/etc/systemd/system/{{service}}.service"

# - name: Starting "{{service}}" service
#   ansible.builtin.systemd_service:
#     name: "{{service}}"
#     daemon_reload: true
#     enabled: true
#     state: started

- name: Setting up Service
  import_tasks: ../../common/tasks/service_setup1.yaml

- name: Preparing to Install Service
  import_tasks: ../../common/tasks/nodejs18.yaml

- name: Service Configuration
  import_tasks: ../../common/tasks/service_config2.yaml

- name: Enabling and Starting Service
  import_tasks: ../../common/tasks/service_start3.yaml
